apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: LoB-Industrializacion-corp
  description: Organización LoB Industrializacion-corp
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: LoB Industrializacion Corp
    email: lob-industrializacion-corp@nomescribas.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  children: [departamento_desarrollo_software]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: LoB-Industrializacion-corp-estructura
  description: Estructura Organización LoB Industrialización, incluye Departamentos, Grupos y Usuarios
spec:
  targets:
    - ./org/LoB_Industrializacion_departamento.yaml
    - ./org/LoB_Industrializacion_group_dev_front.yaml
    - ./org/LoB_Industrializacion_group_dev_back.yaml
    - ./org/LoB_Industrializacion_group_platf_engnr.yaml
    - ./org/LoB_Industrializacion_users.yaml

