apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: LoB-Industrializacion-corp
  description: The LoB Industrializacion organizacion
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: LoB Industrializacion Corp
    email: LoB-Industrializacion-corp@nomescribas.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  children: [departamento_desarrollo_software]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: departamento_desarrolladores_def
  description: Estructura Grupo Desarrolladores LoB-Industrializacion-corp
spec:
  targets:
    - ./org/LoB_Industrializacion_departamento.yaml
    - ./org/LoB_Industrializacion_groups.yaml
    - ./org/LoB_Industrializacion_users.yaml
